### ISSUE TITLE
ERR  not found: make-:

### ISSUE THREAD

**Issue by ajvincent** [mklabs/make#6]
From [travis-ci for my new project, es7-membrane, build 4](https://travis-ci.org/ajvincent/es7-membrane/builds/153967063)

Steps to reproduce:

```
git clone --depth=50 --branch=master https://github.com/ajvincent/es7-membrane.git
# Make sure you have node version 6.x installed
npm update
make travis-ci # everything works fine
node_modules/make/bin/make.js travis-ci # here's where the bug appears
```

It's very possible this is a bug on my end. (I'm new to node/npm.)  Please advise.

Also worth noting:  this error did not cause make.js to exit with a non-zero exit code.  That means travis-ci thought the build passed, when it shouldn't have.

**Comment by danielchatfield** [comment]
Interesting

**Comment by mklabs** [comment]
Hi @ajvincent, I don't think this is a but on your end, this is very likely make.js itself. Thanks for the clear steps to reproduce anyway, I'll try to reproduce and see how it goes.

**Comment by mklabs** [comment]
I think this is due to targets being defined with double colons. `travis-ci::`

Anyway, your Makefile is quite elaborated and make.js won't be able to parse it and execute rules correctly I think. You should use standard make directly, unless you simplify the Makefile drastically.

Unfortunately, make.js is not a standard implementation. make is quite huge, it would need far more work to work as make does, if even possible.

**Comment by ajvincent** [comment]
Thanks for the feedback.  Someone helpfully provided a pull request for my own repo that forces gnu make on me, so my testcase above won't be valid for much longer... :-)

**Comment by mklabs** [comment]
Happy to hear that your problem is solved :+1: :-)
